version: '3.4'

services:
  elasticsearch:
    build:
      context: .
      args:
        ES_VERSION: ${ES_VERSION}
    restart: on-failure
    ports:
      - "9200:9200"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        hard: -1
        soft: -1
    environment:
      ES_JAVA_OPTS: "-Xmx32g -Xms32g"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      xpack.security.enabled: "true"
      indices.memory.index_buffer_size: 8GB
      cluster.routing.allocation.disk.watermark.high: "95%"  # Set high watermark to 95%
      cluster.routing.allocation.disk.watermark.low: "90%"   # Optionally adjust the low watermark
      cluster.info.update.interval: "1m"                    # Set the interval for disk space checks
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
